{% set name = "foxes" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/foxes/archive/v{{ version }}.tar.gz
  sha256: ba4c6b864cdc7219f1764a8d9072d6e4f6120f39ec773692ea17aff47010427c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - matplotlib-base
    - numpy
    - xarray
    - dask-core
    - distributed
    - scipy
    - netcdf4
    - plotly
    - python-kaleido
    - iwopy
    - pymoo

test:
  imports:
    - foxes
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/foxes
  summary: Farm Optimization and eXtended yield Evaluation Software
  description: |
    The software foxes is a modular wind farm simulation and wake
    modelling toolbox which is based on engineering wake models. It
    has many applications, for example wind farm optimization,
    wind farm post-construction analysis, wake model studies, and
    wind farm simulations invoking complex model chains.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SchmJo
