{% set name = "foxes" %}
{% set version = "0.7.4.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/foxes/archive/v{{ version }}.tar.gz
  sha256: 2180d9d693ab4bd7c1edaeda284bc0eb78b0a54dac8ad782f05504ee6e8ecb0c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python
    - matplotlib-base
    - numpy <2
    - pandas
    - xarray
    - dask
    - scipy
    - windrose
    - iwopy
    - pyyaml
  host:
    - python
    - pip
  run:
    - python
    - matplotlib-base
    - numpy <2
    - pandas
    - xarray
    - dask
    - distributed
    - scipy
    - windrose
    - iwopy
    - pyyaml
    - netcdf4
    - pyarrow

test:
  imports:
    - foxes
  requires:
    - pip
    - pytest
    - pymoo
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/foxes
  summary: Farm Optimization and eXtended yield Evaluation Software
  description: |
    The software foxes is a modular wind farm simulation and wake
    modelling toolbox which is based on engineering wake models. It
    has many applications, for example wind farm optimization,
    wind farm post-construction analysis, wake model studies, and
    wind farm simulations invoking complex model chains.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SchmJo
