{% set name = "foxes" %}
{% set version = "0.7.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/foxes/archive/v{{ version }}.tar.gz
  sha256: 95a79ce0a099e3a3f8d6bd9cb3c7c71aee1ead9f51463cc9dba3522ac695aca8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base
    - numpy
    - pandas
    - xarray
    - dask
    - scipy
    - windrose
    - iwopy
    - pyyaml
    - netcdf4
    - pyarrow

test:
  imports:
    - foxes
  requires:
    - pip
    - pytest
    - pymoo
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/foxes
  summary: Farm Optimization and eXtended yield Evaluation Software
  description: |
    The software foxes is a modular wind farm simulation and wake
    modelling toolbox which is based on engineering wake models. It
    has many applications, for example wind farm optimization,
    wind farm post-construction analysis, wake model studies, and
    wind farm simulations invoking complex model chains.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SchmJo
